version: '2'

services:
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:80
        links:
            - ruby-dev:ruby-dev
    #         - postgres:postgres
    # postgres:
    #     image: postgres
    #     restart: always
    #     volumes:
    #         - ./data/postgres:/var/lib/postgresql/data
    #     environment:
    #         PGDATA: /tmp
    #         POSTGRES_DB: db
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: password
    # adminer:
    #     image: adminer
    #     restart: always
    #     environment:
    #         ADMINER_DESIGN: nette
    #         PORT: 8080
    ruby-dev:
        build:
          context: .
          dockerfile: ruby-dev.Dockerfile
        image: ruby-dev
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - .:/wrom
        ports:
            - 3000:3000
    ruby-server:
        build:
          context: .
          dockerfile: ruby-dev.Dockerfile
        image: ruby-dev
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - .:/wrom
        ports:
            - 3000:3000
            - 3001:3001
        command: rails server
    ruby-test:
        build:
          context: .
          dockerfile: ruby-dev.Dockerfile
        image: ruby-dev
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - .:/wrom
        command: rake
